### ISSUE TITLE
AV1 Forward Key Frame forward distance computation

### ISSUE THREAD

**Issue by rbouqueau** [AOMediaCodec/av1-isobmff#31] opened 2018-06-13 19:23 UTC
Could you advise on how to compute the forward distance without digging too deep in the bitstream?

**Comment by tomfinegan** [comment] 2018-06-13 20:41
A muxer that wishes to compute fwd_distance for AV1ForwardKeyFrameSampleGroupEntry must parse AV1 Frame Header OBUs.

The Frame Header OBU must be parsed to determine:
- When you have a Delayed RAP (Random Access Point) frame
  - This is a frame with frame_type equal to KEY_FRAME and show_frame equal to 0.
- The value for fwd_distance. This is the number of frames between the frame with frame_type = KEY_FRAME and show_frame equal to 0, and the frame with show_existing_frame equal to 1 and frame_to_show_map_idx referring to the Delayed RAP frame.

**Comment by cconcolato** [comment] 2018-06-13 20:58
The problem is how to know that `frame_to_show_map_idx` refers to a Key Frame. 

The syntax in `show_existing_frame` refers to the `RefFrameType` array, that is never set in the syntax. [Section 7.20 Frame update process](http://av1-spec.argondesign.com/av1-spec/av1-spec.html#reference-frame-update-process) sets its values, but it's hard to understand when this is called. I see it called in [Decode frame wrapup process](http://av1-spec.argondesign.com/av1-spec/av1-spec.html#decode-frame-wrapup-process) but this is called only when `show_existing_frame` is set, which is weird. I suspect you have to track frame references, and that's not easy, you probably have to parse the entire frame header and run the buffer management algorithm ...

**Comment by cconcolato** [comment] 2018-06-20 23:51
How do you maintain the RefFrameType state? When do you update it? That seems hard from the spec text...

**Comment by tomfinegan** [comment] 2018-07-03 16:41
> How do you maintain the RefFrameType state? When do you update it? That seems hard from the spec text...

Actually, yes, I am not sure how a muxer is going to figure that out. Should we bring this up in a codec WG meeting? (or maybe in the RTC SG?)

**Comment by peterderivaz** [comment] 2018-07-03 20:04
For a show_existing_frame you need to parse:
  show_existing_frame
  frame_to_show_map_idx
You have a recovery point if RefFrameType[ frame_to_show_map_idx ] is KEY_FRAME.

For other frames you need to parse
  frame_type
  ...
  refresh_frame_flags

The refresh_frame_flags lists which reference frames are being updated (with an 8-bit bitmask).
The RefFrameType for each of these reference frames should be set equal to frame_type.

The problem is that you will need to parse the sequence header to be able to skip the syntax elements between frame_type and refresh_frame_flags.

**Comment by cconcolato** [comment] 2018-07-03 21:29
Closing as this seems to be clarified. Reopen if there is a problem.

**Closed by cconcolato** 2018-07-03 21:29 UTC
